/*
 * End-to-end render check: the packaged app, installed on a real Splunk,
 * renders the Airspace Radar inside a Dashboard Studio dashboard in a real
 * (headless) browser, with synthetic aircraft generated by a search.
 *
 * The Studio dashboard is created via REST in beforeAll. Gotchas encoded here
 * (learned on AirspaceWatch/realtime-clock): viz `type` is
 * `<app-dir>.<viz-folder>` with NO `splunk.` prefix, the dashboard XML wrapper
 * needs version="2", and Studio custom vizzes render inside a sandboxed iframe
 * so every assertion must search all frames.
 */
const { test, expect, request } = require('@playwright/test');

const MGMT_URL = process.env.SPLUNK_MGMT_URL || 'https://localhost:8089';
const USER = process.env.SPLUNK_USER || 'admin';
const PASS = process.env.SPLUNK_PASSWORD || 'Changeme1!';
const APP = 'viz-airspace-radar';
const VIEW = 'radar_e2e';

// Three synthetic aircraft within 50 nm of the default centre (53.8, -1.55).
const QUERY =
    '| makeresults count=3 | streamstats count as n ' +
    '| eval hex="E2E".n, callsign="TST00".n, ' +
    'lat=53.8+(n*0.15), lon=-1.55+(n*0.1), ' +
    'altitude_ft=n*10000, heading=n*90, speed_kts=200+n*50 ' +
    '| table hex, callsign, lat, lon, altitude_ft, heading, speed_kts';

const definition = {
    version: '2',
    title: 'Airspace Radar E2E',
    description: 'Playwright render check for the Airspace Radar viz',
    dataSources: {
        primary_ds: {
            type: 'ds.search',
            options: { query: QUERY },
            name: 'synthetic aircraft',
        },
    },
    visualizations: {
        viz_radar: {
            type: `${APP}.airspace_radar`,
            dataSources: { primary: 'primary_ds' },
            options: { homeLabel: 'E2E-HOME', sweepSeconds: 2 },
            title: 'Airspace Radar',
        },
    },
    inputs: {},
    defaults: {},
    layout: {
        type: 'grid',
        options: {},
        structure: [
            { item: 'viz_radar', type: 'block', position: { x: 0, y: 0, w: 600, h: 500 } },
        ],
    },
};

const DASHBOARD_XML =
    `<dashboard version="2" theme="dark"><label>Airspace Radar E2E</label>` +
    `<definition><![CDATA[${JSON.stringify(definition)}]]></definition></dashboard>`;

test.beforeAll(async () => {
    const api = await request.newContext({
        baseURL: MGMT_URL,
        ignoreHTTPSErrors: true,
        httpCredentials: { username: USER, password: PASS },
    });
    // Create, or update if a previous run left it behind.
    const create = await api.post(`/servicesNS/${USER}/${APP}/data/ui/views?output_mode=json`, {
        form: { name: VIEW, 'eai:data': DASHBOARD_XML },
    });
    if (!create.ok()) {
        const update = await api.post(
            `/servicesNS/${USER}/${APP}/data/ui/views/${VIEW}?output_mode=json`,
            { form: { 'eai:data': DASHBOARD_XML } }
        );
        if (!update.ok()) {
            throw new Error(
                `could not create/update dashboard: ${create.status()} then ${update.status()}: ${await update.text()}`
            );
        }
    }
    await api.dispose();
});

// Studio custom vizzes run in a sandboxed iframe — search every frame.
async function findCanvas(page, timeoutMs) {
    const deadline = Date.now() + timeoutMs;
    while (Date.now() < deadline) {
        for (const f of page.frames()) {
            try {
                const h = await f.$('canvas');
                if (h) return { frame: f, handle: h };
            } catch (_) { /* frame may detach mid-poll */ }
        }
        await page.waitForTimeout(2000);
    }
    console.log('frames at timeout:', page.frames().map((f) => f.url()));
    return null;
}

// Sample the viz canvas: painted (non-transparent) pixel count + a checksum
// of the raw pixel bytes so animation shows up even if the count is stable.
async function sampleCanvas(frame) {
    return frame.evaluate(() => {
        const c = document.querySelector('canvas');
        if (!c || c.width === 0) return { painted: -1, sum: 0 };
        const ctx = c.getContext('2d');
        const d = ctx.getImageData(0, 0, c.width, c.height).data;
        let painted = 0;
        let sum = 0;
        for (let i = 0; i < d.length; i += 4) {
            if (d[i + 3] !== 0) painted++;
            sum = (sum + d[i] + d[i + 1] * 7 + d[i + 2] * 13) % 1000000007;
        }
        return { painted, sum };
    });
}

test('Airspace Radar renders and animates on a Studio dashboard', async ({ page }) => {
    const consoleAll = [];
    const consoleErrors = [];
    page.on('console', (msg) => {
        consoleAll.push(`${msg.type()}: ${msg.text()}`.slice(0, 300));
        if (msg.type() === 'error') consoleErrors.push(msg.text());
    });
    page.on('pageerror', (err) => consoleErrors.push(`pageerror: ${err.message}`));
    page.on('response', (r) => {
        if (r.status() >= 400 || /visualization\.js|airspace_radar/.test(r.url())) {
            console.log(`HTTP ${r.status()} ${r.url()}`);
        }
    });

    // Splunk web form login
    await page.goto('/en-GB/account/login');
    await page.fill('input[name="username"]', USER);
    await page.fill('input[name="password"]', PASS);
    await page.press('input[name="password"]', 'Enter');
    await page.waitForURL(/\/(app|launcher|home)/, { timeout: 60000 });

    // Open the dashboard and wait for the viz canvas (in any frame)
    await page.goto(`/en-GB/app/${APP}/${VIEW}`);
    const found = await findCanvas(page, 120000);
    if (!found) {
        console.log('--- console messages (last 50) ---');
        consoleAll.slice(-50).forEach((l) => console.log(l));
        for (const f of page.frames()) {
            if (f === page.mainFrame()) continue;
            console.log(`--- frame content: ${f.url()} ---`);
            try { console.log((await f.content()).slice(0, 3000)); }
            catch (e) { console.log('frame content unavailable:', e.message); }
        }
    }
    expect(found, 'no canvas found in any frame — see logged diagnostics').not.toBeNull();

    // The scope actually painted (rings, sweep, blips), not just an empty canvas
    let sample = { painted: 0, sum: 0 };
    for (let i = 0; i < 30 && sample.painted < 1000; i++) {
        sample = await sampleCanvas(found.frame);
        if (sample.painted < 1000) await page.waitForTimeout(2000);
    }
    console.log(`painted pixels: ${sample.painted}`);
    expect(sample.painted).toBeGreaterThan(1000);

    // The sweep animates: two samples a moment apart must differ
    const before = await sampleCanvas(found.frame);
    await page.waitForTimeout(700);
    const after = await sampleCanvas(found.frame);
    console.log(`animation check: sum ${before.sum} -> ${after.sum}`);
    expect(after.sum).not.toBe(before.sum);

    // Render proof artifact
    await page.screenshot({ path: 'e2e-results/radar-render.png' });

    // Surface (but tolerate) console noise; hard-fail only on our own module
    const vizErrors = consoleErrors.filter((e) => /airspace_radar|visualization\.js/.test(e));
    console.log(`console errors total=${consoleErrors.length}, viz-specific=${vizErrors.length}`);
    expect(vizErrors).toEqual([]);
});
